test_rotate: 
	g++ test_rotate.cc util.cc ../split.cc Pharse.cc -o test_rotate
main:
	g++ main.cc util.cc ../split.cc Pharse.cc -o main
test_left_part_len:
	g++ test_left_part_len.cc util.cc ../split.cc -o test_left_part_len
