CXX = g++
make all: drill_comparing_numbers drill_min_max 

drill_comparing_numbers: ../std_lib_facilities.h drill_comparing_numbers.cc

drill_min_max: ../std_lib_facilities.h drill_min_max.cc

drill_units: ../std_lib_facilities.h drill_units.cc
clobber: 
		rm -f *.o \
		  drill_comparing_numbers min_max drill_units