CXX	=	g++
CXX = g++
CC = g++
CXXFLAGS =  -Wall -I. -I../ -I../../chapter08

Student_info.o: Student_info.cc Student_info.h
14-1: Student_info.o ../Core.o ../grade.o  ../read_hw.o 

clobber: 
	rm -rf *.o 14-1
